In [1]:
import pandas as pd

pd.read_json('output.json')

     timings_nsga_ii  timings_nsga_iii  timings_moead
0           2.841747          2.854554      27.868228
1           2.390528          2.859022      26.023351
2           2.101516          2.259927      22.953685
3           2.120759          2.318197      23.570199
4           2.112749          2.274081      23.072323
..               ...               ...            ...
195         2.966076          3.225109      32.644677
196         2.887003          3.315896      32.063802
197         2.847880          3.175494      32.405217
198         2.992172          3.075410      31.721970
199         2.881703          3.064527      32.318877

[200 rows x 3 columns]